name: Bandit Security Scan
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Vérifier le code
        uses: actions/checkout@v3

      - name: Configurer Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Installer les dépendances
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip install bandit

      - name: Analyse de sécurité avec Bandit
        run: |
          source venv/bin/activate
          bandit -r . --severity-level high --exclude "./venv" # Dependabot already analyzes dependencies
